#!/usr/bin/bash

if [ "$1" == "" ]; then
  echo "Output directory was not provided"
  exit 1
fi

if [ -e "$1" ]; then
  echo "Output directory already exists"
  exit 1
fi

mkdir -p "$1"
cp -r /usr/local/include/aether/wasm/* "$1"
