#!/usr/bin/bash

if [ "$1" == "" ]; then
  echo "Output directory was not provided"
  exit 1
fi

if [ "$2" == "" ]; then
  echo "Input directory was not provided"
  exit 1
fi

if [ "$3" == "" ]; then
  echo "Input file was not provided"
  exit 1
fi

rm -rf "$1"
mkdir -p "$1"
cp -r /usr/include/aether/wasm/* "$1"
cp -r "$2"/* "$1"
aether -c "$1"/app.abc "$3"
